"""add is_public field to Litter model

Revision ID: 12253952763f
Revises: 309c6ed84972
Create Date: 2024-09-16 12:26:15.439135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12253952763f'
down_revision = '309c6ed84972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
