"""Added Vet Appointment Catagories

Revision ID: 28d1ca30871b
Revises: c69eb0afc9d8
Create Date: 2024-09-17 05:04:46.788615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d1ca30871b'
down_revision = 'c69eb0afc9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Enum('CHECKUP', 'VACCINATION', 'SURGERY', 'OTHER', name='appointmentcategory'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_appointment', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
