"""empty message

Revision ID: 309c6ed84972
Revises: e86e9aa8daeb
Create Date: 2024-09-16 12:06:03.167386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309c6ed84972'
down_revision = 'e86e9aa8daeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
