"""Add is_featured to BlogPost

Revision ID: 3d17f92ffd07
Revises: b62c5494e9cc
Create Date: 2024-09-23 03:06:11.042185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d17f92ffd07'
down_revision = 'b62c5494e9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
