"""Add account type to User model

Revision ID: 80b3e26a7a8b
Revises: d98fb3cef696
Create Date: 2024-09-20 08:47:45.787189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b3e26a7a8b'
down_revision = 'd98fb3cef696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.Enum('FREE', 'BASIC', 'PREMIUM', name='accounttype'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    # ### end Alembic commands ###
