"""empty message

Revision ID: 930e6b88b0fb
Revises: 12253952763f
Create Date: 2024-09-16 18:12:06.476238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930e6b88b0fb'
down_revision = '12253952763f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('AVAILABLE_NOW', 'AVAILABLE_SOON', 'RESERVED', 'SOLD', 'NOT_FOR_SALE', name='dogstatus'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
