"""Add price field to Dog model

Revision ID: 96d4e5c34073
Revises: 930e6b88b0fb
Create Date: 2024-09-16 19:50:58.689945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d4e5c34073'
down_revision = '930e6b88b0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dog', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
