"""Update BlogPost model for database image storage

Revision ID: b62c5494e9cc
Revises: 2c2512d1d878
Create Date: 2024-09-22 16:46:01.824281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62c5494e9cc'
down_revision = '2c2512d1d878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('image_mimetype', sa.String(length=50), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('image_mimetype')
        batch_op.drop_column('image_filename')
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
