"""Updated Message Model

Revision ID: e86e9aa8daeb
Revises: ae6634dc72d4
Create Date: 2024-09-15 10:32:40.879789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86e9aa8daeb'
down_revision = 'ae6634dc72d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conversation_id', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('conversation_id')

    # ### end Alembic commands ###
